hist(x)
Metrics <- read.csv("~/Downloads/Metrics.csv")
View(Metrics)
hist(Metrics$X..of.Relevant.Mentions)
hist(Metrics$X..of.Mentions)
hist(Metrics$X..of.Relevant.Mentions, xlab= "relevent mentions", border="blue", col="pink")
hist(Metrics$X, main = "projects", border = "green", col = "gold")
barplot(Metrics$X..of.Mentions)
barplot(Metrics$X..of.Relevant.Mentions)
summary(Metrics$X..of.Relevant.Mentions)
summary(Metrics)
str(Metrics)
Metrics$Tense.of.Language != Metrics$X
hist(Metrics$X..of.Relevant.Mentions)
hist(Metrics$X..of.Relevant.Mentions, main = "Relevant Mentions", xlab = "Mentions", col = "green")
